$('#new_product').click(function(){
  window.location="http://localhost:5224/ebaytester/new_product_upload.html";
});
$('#modify').click(function(){
  window.location="http://localhost:5224/ebaytester/product_modify.html";
});
$('#Delete').click(function(){
  window.location="http://localhost:5224/ebaytester/product_delete.html";
});
$('#change_address').click(function(){
  window.location="http://localhost:5224/ebaytester/address_form_seller.html";
});
$('#AddDeal').click(function(){
	  window.location="http://localhost:5224/ebaytester/addDealToProduct.html";
	});
